# Generated by Django 5.2.1 on 2025-06-07 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadershipSessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_datetime', models.DateTimeField()),
                ('timezone', models.CharField(max_length=50)),
                ('goals', models.TextField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_or_website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sessionduration')),
                ('session_format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sessionformat')),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sessiontype')),
            ],
        ),
    ]
