# Generated by Django 5.2.1 on 2025-06-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipsessionbooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadershipsessionbooking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadershipsessionbooking',
            name='is_mentor_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadershipsessionbooking',
            name='is_session_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadershipsessionbooking',
            name='mentor_confirmation_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='leadershipsessionbooking',
            name='session_completion_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
