# Generated by Django 5.2.1 on 2025-06-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_leadershipsessionbooking_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipsessionbooking',
            name='is_session_held',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
