# Generated by Django 5.2.1 on 2025-06-29 00:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leadershipsessionbooking_is_session_held'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipsessionbooking',
            name='token_generated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionduration',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
