# Generated by Django 5.2.1 on 2025-09-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sendmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipsessionbooking',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
